import type { Company } from '../types';

const MOCK_DATABASE: Omit<Company, 'sourceUrl'>[] = [
  {
    id: 0,
    company: 'Toss Bank',
    location: '강남구 테헤란로 142',
    lat: 37.496881,
    lng: 127.027741,
    salary: '7,000+',
    keywords: ['React', '금융', 'Toss Core'],
    deadline: 'D-7',
    description: '- 금융의 모든 순간을 쉽고 간편하게 만드는 Frontend 개발\n- TypeScript 기반의 웹 앱 설계 및 구현\n- 사용자 중심의 UI/UX 개선 및 성능 최적화',
  },
  {
    id: 1,
    company: 'Dangn',
    location: '서초구 강남대로 465',
    lat: 37.495056,
    lng: 127.035667,
    salary: '6,500+',
    keywords: ['Vue', '지역기반', 'Hyperlocal'],
    deadline: 'D-12',
    description: '- 당근 서비스의 웹 프론트엔드 개발\n- 지역 커뮤니티 활성화를 위한 신규 기능 개발\n- Vue.js 및 Nuxt.js 기반의 서비스 운영 및 개선',
  },
  {
    id: 2,
    company: 'Kakao',
    location: '제주 첨단로 242',
    lat: 33.386598,
    lng: 126.541806,
    salary: '5,500+',
    keywords: ['AI', 'Platform', 'Large Scale'],
    deadline: 'D-3',
    description: '- 카카오의 다양한 서비스 웹 개발\n- 대규모 트래픽 처리를 위한 아키텍처 설계\n- 최신 웹 기술을 활용한 프로토타이핑 및 개발',
  },
  {
    id: 3,
    company: 'Naver',
    location: '성남시 분당구 불정로 6',
    lat: 37.365019,
    lng: 127.106357,
    salary: '6,000+',
    keywords: ['Search', 'Backend', 'Optimization'],
    deadline: '상시',
    description: '- 네이버 검색 및 AI 서비스의 UI 개발\n- Svelte, React 등 다양한 기술 스택 활용\n- 웹 접근성 및 성능 표준 준수를 위한 노력',
  },
  {
    id: 4,
    company: 'Coupang',
    location: '송파구 송파대로 570',
    lat: 37.512891,
    lng: 127.063045,
    salary: '7,500+',
    keywords: ['E-commerce', 'AWS', 'Java'],
    deadline: 'D-20',
    description: '- 쿠팡의 이커머스 플랫폼 프론트엔드 개발\n- A/B 테스트를 통한 사용자 경험 데이터 분석 및 개선\n- AWS 기반의 클라우드 환경에서의 개발',
  },
  {
    id: 5,
    company: 'Woowa Bros',
    location: '송파구 위례성대로 2',
    lat: 37.499219,
    lng: 127.021903,
    salary: '6,800+',
    keywords: ['Spring', 'MSA', 'Food Tech'],
    deadline: '상시',
    description: '- 배달의민족 서비스의 웹 프론트엔드 개발\n- MSA 환경에서의 서비스 개발 및 운영\n- 코드 리뷰 및 페어 프로그래밍을 통한 동료 성장 지원',
  },
  {
    id: 6,
    company: 'Line',
    location: '성남시 분당구 황새울로200번길',
    lat: 37.365058,
    lng: 127.106439,
    salary: '6,200+',
    keywords: ['Messenger', 'Global', 'Fintech'],
    deadline: 'D-5',
    description: '- 글로벌 메신저 라인의 웹 서비스 개발\n- 핀테크, 블록체인 등 신규 사업 관련 웹 개발\n- 다국어 및 현지화 지원을 위한 개발',
  },
  {
    id: 7,
    company: 'Viva Republica',
    location: '강남구 테헤란로 131',
    lat: 37.498981,
    lng: 127.028211,
    salary: '7,200+',
    keywords: ['Toss', 'TypeScript', 'Innovation'],
    deadline: 'D-10',
    description: '- 토스 서비스의 웹 프론트엔드 개발\n- 복잡한 금융 로직을 단순하고 직관적인 UI로 구현\n- 높은 수준의 코드 품질과 테스트 커버리지 유지',
  },
];

export const generateMockData = (urls: string[]): Company[] => {
  return urls.map((url, index) => ({
    ...MOCK_DATABASE[index % MOCK_DATABASE.length],
    sourceUrl: url,
  }));
};

export const COMPANY_DETAILS: Record<string, any> = {
  '0': {
    size: '1,500명',
    funding: '2.1조원',
    revenue: '5,372억원 (2022)',
    news: '토스뱅크, 출범 2년만에 흑자 전환 성공',
    projects: '모바일 뱅킹 앱 고도화',
    links: { blog: 'https://blog.toss.im', homepage: 'https://toss.im' },
  },
  '1': {
    size: '500명',
    funding: '2,150억원',
    revenue: '비공개',
    news: '당근, 월간 활성 이용자 1,800만 돌파',
    projects: '지역 커뮤니티 서비스 확장',
    links: { blog: 'https://medium.com/daangn', homepage: 'https://www.daangn.com' },
  },
  '2': {
    size: '3,900명',
    funding: '상장',
    revenue: '7.1조원 (2022)',
    news: '카카오, AI 챗봇 "코GPT 2.0" 공개 예정',
    projects: '카카오톡 채널 기능 강화',
    links: { blog: 'https://tech.kakao.com', homepage: 'https://www.kakaocorp.com' },
  },
  '3': {
    size: '4,500명',
    funding: '상장',
    revenue: '8.2조원 (2022)',
    news: '네이버, 하이퍼클로바X 기반 서비스 확대',
    projects: '차세대 검색 엔진 개발',
    links: { blog: 'https://d2.naver.com', homepage: 'https://www.navercorp.com' },
  },
  '4': {
    size: '63,000명',
    funding: '상장',
    revenue: '32조원 (2022)',
    news: '쿠팡, 대만 로켓배송 서비스 확장',
    projects: '물류 자동화 시스템 고도화',
    links: { blog: 'https://medium.com/coupang-tech', homepage: 'https://www.aboutcoupang.com' },
  },
  '5': {
    size: '2,000명',
    funding: '딜리버리히어로 인수',
    revenue: '2.9조원 (2022)',
    news: '배달의민족, B마트 서비스 지역 확대',
    projects: '배민1플러스 서비스 런칭',
    links: { blog: 'https://techblog.woowahan.com', homepage: 'https://www.woowahan.com' },
  },
  '6': {
    size: '9,000명',
    funding: '상장',
    revenue: '2.4조원 (2022)',
    news: '라인, NFT 마켓플레이스 "도시" 출시',
    projects: '라인 블록체인 플랫폼 개발',
    links: { blog: 'https://engineering.linecorp.com', homepage: 'https://linepluscorp.com' },
  },
  '7': {
    size: '1,800명',
    funding: '2.1조원',
    revenue: '1.1조원 (2022)',
    news: '토스, 증권 및 페이먼츠 사업 확장',
    projects: '통합 금융 플랫폼 구축',
    links: { blog: 'https://blog.toss.im', homepage: 'https://toss.im' },
  },
};

export const DEFAULT_RESUME_BLOCKS = [
  { id: 1, type: 'h2' as const, text: '김철수 | Frontend Developer' },
  {
    id: 2,
    type: 'p' as const,
    text: '3년차 프론트엔드 개발자 김철수입니다. 복잡한 비즈니스 요구사항을 직관적이고 효율적인 UI/UX로 구현하는 데 강점이 있습니다. 새로운 기술을 배우고 팀과 지식을 공유하는 것을 좋아합니다.',
  },
  { id: 3, type: 'h2' as const, text: 'Work Experience' },
  { id: 4, type: 'h3' as const, text: 'Gemini Corp (2022.03 - 현재)' },
  {
    id: 5,
    type: 'p' as const,
    text: '금융 데이터 시각화 대시보드 개발을 담당했습니다. React와 D3.js를 사용하여 대용량 데이터를 실시간으로 차트와 그래프로 표현했으며, 컴포넌트 최적화를 통해 초기 로딩 속도를 60% 이상 개선했습니다.',
  },
  { id: 6, type: 'h3' as const, text: 'AI Inc. (2020.01 - 2022.02)' },
  {
    id: 7,
    type: 'p' as const,
    text: 'Vue.js 기반의 이커머스 플랫폼 프론트엔드 개발팀의 일원으로 참여했습니다. 장바구니, 결제, 주문 내역 등 주요 사용자 플로우를 개발하고 UI/UX 개선에 기여했습니다.',
  },
  { id: 8, type: 'h2' as const, text: 'Projects' },
  { id: 9, type: 'h3' as const, text: '개인 포트폴리오 사이트' },
  {
    id: 10,
    type: 'p' as const,
    text: 'Next.js와 Tailwind CSS를 사용하여 제작한 반응형 개인 웹사이트입니다. 저의 프로젝트와 기술 스택을 소개하며, Vercel을 통해 배포 및 관리하고 있습니다.',
  },
  { id: 11, type: 'h2' as const, text: 'Skills' },
  {
    id: 12,
    type: 'p' as const,
    text: 'Languages: JavaScript (ES6+), TypeScript, HTML5, CSS3\nFrameworks: React, Next.js, Vue.js\nLibraries: Redux, Zustand, React Query, D3.js, Tailwind CSS\nTools: Git, Webpack, Vite, Figma',
  },
];
